/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
//package javaapplication;

/**
 *
 * @author VIGNESH
 */

 import java.awt.Panel;
import java.sql.ResultSet;
import java.util.ArrayList;
 import java.util.List;

import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
 
 import PanelCode.PanelCode;
import MainCrud.MainCrudOperation;
public class RequestView extends javax.swing.JPanel {

    /**
     * Creates new form RequestView
     */
    public RequestView() {
        initComponents();
        show_user();
    }
    public int col(){
        rs=MainCrudOperation.DisplayRequest();
        try
        {
        return(rs.getMetaData().getColumnCount());
        }
        catch(Exception e)
        {
            e.printStackTrace();
            return 0;
        }
    }
    public List<Object[]> booklist(){
        List<Object[]> data = new ArrayList<>();
        try
        {
        // rs=MainCrudOperation.Display();

        int columns = col();
        
        // Initialize a 2D list to store the data
        
// Iterate through the result set
while (rs.next()) {
    // Create a list to store the values of the current row
    List<Object> rowData = new ArrayList<>();
    // Retrieve column values
    for (int i = 1; i <= columns; i++) {
        Object columnValue = rs.getObject(i);
        // Add the column value to the current row data
        rowData.add(columnValue);
    }
    // Convert the row data list to an array and add it to the data list
    data.add(rowData.toArray());
}
}
catch(Exception e)
{
    e.printStackTrace();
}
return data;
}

public void show_user()
{
    try{

        List<Object[]> data = booklist();
        int columns=col();
        rs=MainCrudOperation.DisplayRequest();
    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
    Object[] columnNames = new Object[columns];
for (int i = 1; i <= columns; i++) {
    columnNames[i - 1] = rs.getMetaData().getColumnName(i);
    model.addRow(columnNames);
}
model = new DefaultTableModel(data.toArray(new Object[0][]), columnNames);
jTable1.setModel(model);

// Define column types and editability
Class[] types = {String.class, String.class, String.class, Integer.class};
boolean[] canEdit = {false, false, false, false};

// Set column types and editability using a custom table model
CustomTableModel customModel = new CustomTableModel(data.toArray(new Object[0][]), columnNames, types, canEdit);
jTable1.setModel(customModel);

}
catch (Exception e)
{}
}

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
try
{
    jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Back");

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 51));
        jButton2.setText("Accept Request\n");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
     {//
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                        frame.dispose();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) 
    {//
        AcceptRequest.main(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private static ResultSet rs;
    // End of variables declaration//GEN-END:variables
    static PanelCode obj = new PanelCode();
    public static void main(String[] args) {
   
        obj.Panel(new RequestView());
        
     }
}


class CustomTableModel extends DefaultTableModel {

    private final Class[] types;
    private final boolean[] canEdit;

    public CustomTableModel(Object[][] data, Object[] columnNames, Class[] types, boolean[] canEdit) {
        super(data, columnNames);
        this.types = types;
        this.canEdit = canEdit;
    }

   
   
}