/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
// package javaapplication;

import java.util.ArrayList;
import java.util.List;
import java.sql.*;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import PanelCode.PanelCode;
import MainCrud.MainCrudOperation;
/**
 *
 * @author VIGNESH
 */
public class StuBooks extends javax.swing.JPanel {

    /**
     * Creates new form StuBooks
     */
    public StuBooks() {
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public int col()
        {
        rs=MainCrudOperation.DisplayUserBook();
        try
        {
        return(rs.getMetaData().getColumnCount());
        }
        catch(Exception e)
        {
            e.printStackTrace();
            return 0;
        }
    }
    public List<Object[]> booklist(){
        List<Object[]> data = new ArrayList<>();
        try
        {
        // rs=MainCrudOperation.Display();

        int columns = col();
        
        // Initialize a 2D list to store the data
        
// Iterate through the result set
while (rs.next()) {
    // Create a list to store the values of the current row
    List<Object> rowData = new ArrayList<>();
    // Retrieve column values
    for (int i = 1; i <= columns; i++) {
        Object columnValue = rs.getObject(i);
        // Add the column value to the current row data
        rowData.add(columnValue);
    }
    // Convert the row data list to an array and add it to the data list
    data.add(rowData.toArray());
}
}
catch(Exception e)
{
    e.printStackTrace();
}
return data;
}

public void show_user()
{
    try{
    List<Object[]> data = booklist();
    int columns=col();
    rs=MainCrudOperation.DisplayUserBook();
    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
    Object[] columnNames = new Object[columns];
    for (int i = 1; i <= columns; i++) {
    columnNames[i - 1] = rs.getMetaData().getColumnName(i);
    model.addRow(columnNames);
    }
    model = new DefaultTableModel(data.toArray(new Object[0][]), columnNames);
    jTable1.setModel(model);
    
    // Define column types and editability
    Class[] types = {String.class, String.class, String.class, Integer.class};
    boolean[] canEdit = {false, false, false, false};
    
    // Set column types and editability using a custom table model
    CustomTableModel customModel = new CustomTableModel(data.toArray(new Object[0][]), columnNames, types, canEdit);
    jTable1.setModel(customModel);
    
}
catch(Exception e)
{
    e.printStackTrace();
}
}
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        // jTable1.setAutoCreateRowSorter(true);
        
      
        


        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Books");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Action performed when Library Books button is clicked
        // System.out.println("Library Books button clicked");
        
        // StuBooksView.main(null);

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        // Call the method to open Library Books panel or perform other actions
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private static ResultSet rs;
    static PanelCode obj = new PanelCode();
    public static void main(String[] args) {
   
        obj.Panel(new StuBooks());
        
     }
}
