/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
//package javaapplication;

import java.util.ArrayList;
import java.util.List;
import java.sql.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import MainCrud.MainCrudOperation;
import PanelCode.PanelCode;

/**
 *
 * @author VIGNESH
 */
public class StuBooksView extends javax.swing.JPanel {

    /**
     * Creates new form StuBooksView
     */
    public StuBooksView() {
        initComponents();
        show_user(1);
    }
    private static String[] session;
    public int col(){
        rs=MainCrudOperation.Display();
        try
        {
        return(rs.getMetaData().getColumnCount());
        }
        catch(Exception e)
        {
            e.printStackTrace();
            return 0;
        }
    }
    public List<Object[]> booklist(){
        List<Object[]> data = new ArrayList<>();
        try
        {
        // rs=MainCrudOperation.Display();

        int columns = col();
        
        // Initialize a 2D list to store the data
        
// Iterate through the result set
while (rs.next()) {
    // Create a list to store the values of the current row
    List<Object> rowData = new ArrayList<>();
    // Retrieve column values
    for (int i = 1; i <= columns; i++) {
        Object columnValue = rs.getObject(i);
        // Add the column value to the current row data
        rowData.add(columnValue);
    }
    // Convert the row data list to an array and add it to the data list
    data.add(rowData.toArray());
}
}
catch(Exception e)
{
    e.printStackTrace();
}
return data;
}
public List<Object[]> booksearch(){
    List<Object[]> data = new ArrayList<>();
    try {
        ResultSet rs1=MainCrudOperation.Search(Integer.parseInt(jTextField1.getText()));
            int columns = col();
                // Create a list to store the values of the current row
                List<Object> rowData = new ArrayList<>();
                // Retrieve column values
                for (int i = 1; i <= columns; i++) {
                    Object columnValue = rs1.getObject(i);
                    // System.out.println(rs1.getObject(i));
                    // Add the column value to the current row data
                    rowData.add(columnValue);
                }
                // Convert the row data list to an array and add it to the data list
                data.add(rowData.toArray());
    } catch (Exception e) {
        // TODO: handle exception
        e.printStackTrace();
    }
return data;
}

public void show_user(int flag)
{List<Object[]> data= new ArrayList<>();
    try{
        if(flag==1)
        {
            data = booklist();
        }
        else
        {
            data=booksearch();
        }
    int columns=col();
    rs=MainCrudOperation.Display();
    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
    Object[] columnNames = new Object[columns];
    for (int i = 1; i <= columns; i++) {
    columnNames[i - 1] = rs.getMetaData().getColumnName(i);
    model.addRow(columnNames);
    }
    model = new DefaultTableModel(data.toArray(new Object[0][]), columnNames);
    jTable1.setModel(model);
    
    // Define column types and editability
    Class[] types = {String.class, String.class, String.class, Integer.class};
    boolean[] canEdit = {false, false, false, false};
    
    // Set column types and editability using a custom table model
    CustomTableModel customModel = new CustomTableModel(data.toArray(new Object[0][]), columnNames, types, canEdit);
    jTable1.setModel(customModel);
    
}
catch(Exception e)
{
    e.printStackTrace();
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome!!!");

        jTable1.setAutoCreateRowSorter(true);
        
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 102));
        jButton2.setText("Issue Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 0));
        jButton3.setText("Search");

        jLabel2.setText("Book ID:");

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Action performed when Library Books button is clicked
        // System.out.println("Library Books button clicked");
        
        // StuBooksView.main(null);

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        // Call the method to open Library Books panel or perform other actions
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Action performed when Library Books button is clicked
        // System.out.println("Library Books button clicked");

        SendRequest.main(session);

        // Call the method to open Library Books panel or perform other actions
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Action performed when Library Books button is clicked
        // System.out.println("Library Books button clicked");
        // System.out.println("btn1");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        if(jTextField1.getText().equals(""))
        {
            show_user(1);
        }
        else{
            try
            {
                Integer.parseInt(jTextField1.getText());
                show_user(2);
            } catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "Enter a valid Book ID", 
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextField1.setText(null);


        // Call the method to open Library Books panel or perform other actions
    }



    static PanelCode obj = new PanelCode();
    public static void main(String[] args) {
        session=args;
        obj.Panel(new StuBooksView());
        
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private static ResultSet rs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
